name: Docker Image Release

on:
  workflow_run:
    workflows: ["Build Web"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t dominiquekl/printerlynx_web:latest .
        docker push dominiquekl/printerlynx_web:latest
